### ISSUE TITLE
'Architecture' definition

### ISSUE THREAD

**Issue by tanvisharma** [UIUC-IMC/UIUC-IMC-Benchmarking#2]
What is the intuition behind architecture column, particularly the difference between SRAM and Digital? For example, both index 67 and 69 are Digital CIM macros, but 67 has 'Digital' architecture while 69 has 'SRAM'.

**Comment by soonhahwang** [comment]
Architectures are mostly to distinguish what type of memory was used in the CIM macros. Digital on the other hand means a digital accelerator that doesn't use CIM macro. In the case of index 67, we viewed this work to be rather a near-memory computing then an in-memory computing, which we distinguished as a Digital (Accelerator).
